const { DataTypes } = require("sequelize");
const sequelize = require("../config/database");

const ServicomComplaint = sequelize.define("ServicomComplaint", {
  id:               { type: DataTypes.INTEGER.UNSIGNED, autoIncrement: true, primaryKey: true },
  complaint_number: { type: DataTypes.STRING(60), allowNull: false, unique: true },
  zone_id:          { type: DataTypes.INTEGER.UNSIGNED, allowNull: true },
  state_id:         { type: DataTypes.INTEGER.UNSIGNED, allowNull: true },
  reporting_month:  { type: DataTypes.TINYINT.UNSIGNED, allowNull: true },
  reporting_year:   { type: DataTypes.SMALLINT.UNSIGNED, allowNull: true },
  entry_date:       { type: DataTypes.DATEONLY, allowNull: true },
  complaint_date:   { type: DataTypes.DATEONLY, allowNull: false },
  complaint_type:   { type: DataTypes.STRING(80), allowNull: true },
  complaint_against: { type: DataTypes.STRING(80), allowNull: true },
  complaint_category: { type: DataTypes.STRING(80), allowNull: true },
  category_code:    { type: DataTypes.STRING(30), allowNull: true },
  complaint_domain: { type: DataTypes.STRING(80), allowNull: true },
  domain_code:      { type: DataTypes.STRING(30), allowNull: true },
  offence_reference: { type: DataTypes.STRING(30), allowNull: true },
  priority_rating:  { type: DataTypes.STRING(20), allowNull: true },
  date_received:    { type: DataTypes.DATEONLY, allowNull: true },
  transmission_route: { type: DataTypes.STRING(80), allowNull: true },
  complainant_category: { type: DataTypes.STRING(80), allowNull: true },
  complainant_id:   { type: DataTypes.STRING(100), allowNull: true },
  complainant_name: { type: DataTypes.STRING(200), allowNull: true },
  complainant_organization: { type: DataTypes.STRING(200), allowNull: true },
  complainant_phone: { type: DataTypes.STRING(80), allowNull: true },
  complainant_nhis_id: { type: DataTypes.STRING(100), allowNull: true },
  complainant_hmo_id: { type: DataTypes.INTEGER.UNSIGNED, allowNull: true },
  complainant_hcf_id: { type: DataTypes.INTEGER.UNSIGNED, allowNull: true },
  respondent_category: { type: DataTypes.STRING(80), allowNull: true },
  respondent_id:    { type: DataTypes.STRING(100), allowNull: true },
  respondent_name:  { type: DataTypes.STRING(200), allowNull: true },
  respondent_organization: { type: DataTypes.STRING(200), allowNull: true },
  respondent_phone: { type: DataTypes.STRING(80), allowNull: true },
  respondent_nhis_id: { type: DataTypes.STRING(100), allowNull: true },
  respondent_hmo_id: { type: DataTypes.INTEGER.UNSIGNED, allowNull: true },
  respondent_hcf_id: { type: DataTypes.INTEGER.UNSIGNED, allowNull: true },
  officer_assigned: { type: DataTypes.STRING(150), allowNull: true },
  investigation_start_date: { type: DataTypes.DATEONLY, allowNull: true },
  status: {
    type: DataTypes.STRING(50),
    allowNull: false,
    defaultValue: "New/Acknowledged",
  },
  actions_taken:    { type: DataTypes.STRING(150), allowNull: true },
  actions_details:  { type: DataTypes.TEXT, allowNull: true },
  escalated:        { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false },
  escalation_level: { type: DataTypes.STRING(80), allowNull: true },
  escalation_date:  { type: DataTypes.DATEONLY, allowNull: true },
  escalated_to:     { type: DataTypes.STRING(80), allowNull: true },
  resolution_days:  { type: DataTypes.INTEGER.UNSIGNED, allowNull: true },
  resolution_within_sla: { type: DataTypes.BOOLEAN, allowNull: true },
  date_closed:      { type: DataTypes.DATEONLY, allowNull: true },
  outcome:          { type: DataTypes.STRING(80), allowNull: true },
  remarks:          { type: DataTypes.TEXT, allowNull: true },
  facility_id:      { type: DataTypes.INTEGER.UNSIGNED, allowNull: true },
  facility_name:    { type: DataTypes.STRING(200), allowNull: true },
  visit_id:         { type: DataTypes.INTEGER.UNSIGNED, allowNull: true },
  category:         { type: DataTypes.STRING(80), allowNull: true },
  description:      { type: DataTypes.TEXT, allowNull: true },
  assigned_officer: { type: DataTypes.STRING(150), allowNull: true },
  resolution_notes: { type: DataTypes.TEXT, allowNull: true },
  resolution_date:  { type: DataTypes.DATEONLY, allowNull: true },
  created_by:       { type: DataTypes.STRING(100), allowNull: true },
  created_by_staff_id: { type: DataTypes.STRING(50), allowNull: true },
}, { tableName: "servicom_complaints", modelName: "ServicomComplaint" });

module.exports = ServicomComplaint;
